apiVersion: v1
kind: Service
metadata:
  name: {{ include "basic-postgres-chart.fullname" . }}
  labels:
    {{- include "basic-postgres-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "basic-postgres-chart.selectorLabels" . | nindent 4 }}
