apiVersion: v2
name: stack-902
version: 0.1.0
dependencies:
    - name: traefik
      version: "35.4.0"
      repository: "https://helm.traefik.io/traefik"
    - name: ingress-nginx
      version: "4.10.0"
      repository: "https://kubernetes.github.io/ingress-nginx"