controller:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
      metrics:
        port: 10254
        targetPort: metrics
        protocol: TCP
        name: metrics

  # Optionnel : activer le port metrics dans le pod
  metricsPort: 10254

defaultBackend:
  enabled: true
