traefik:
  dashboard:
    enabled: true
  entryPoints:
    web:
      address: ":8000"
    websecure:
      address: ":8443"
    metrics:
      address: ":9090"
  metrics:
    prometheus:
      enabled: true
      entryPoint: metrics
      serviceMonitor:
        enabled: true
        namespace: default # Assurez-vous que ce namespace est correct
  ports:
    web:
      port: 8000
      expose:
        default: true
      exposedPort: 8000
      protocol: TCP
      nodePort: 31080
    websecure:
      port: 8443
      expose:
        default: true
      exposedPort: 8443
      protocol: TCP
      nodePort: 31443
    metrics:
      port: 9090
      expose:
        default: true
      exposedPort: 9090
      protocol: TCP
      nodePort: 31910
  service:
    enabled: true
    type: NodePort

prometheus:
  # v-- NOUVELLE SECTION CI-DESSOUS --v
  crds:
    enabled: true # <-- MODIFICATION : Indique au chart d'installer les CRDs requises (ServiceMonitor, etc.)
  # ^-- NOUVELLE SECTION CI-DESSUS --^
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}