controller:
  metrics:
    enabled: true
    service:
      enabled: true
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      port: 10254
      targetPort: 10254
      type: ClusterIP

  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
      metrics:
        port: 10254
        targetPort: 10254
        protocol: TCP
        name: metrics

  extraArgs:
    enable-prometheus-metrics: "true"

defaultBackend:
  enabled: true
