dashboard:
  enabled: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":9100"

metrics:
  prometheus:
    enabled: true
    entryPoint: metrics

service:
  ports:
    web:
      port: 80
      protocol: TCP
      targetPort: web
    websecure:
      port: 443
      protocol: TCP
      targetPort: websecure
    metrics:
      port: 9100
      protocol: TCP
      targetPort: metrics

serviceMonitor:
  enabled: true
  additionalLabels: {}
  interval: 10s
  scrapeTimeout: 10s
