traefik:
  dashboard:
    enabled: true

  entryPoints:
    web:
      address: ":80"
    websecure:
      address: ":443"
    metrics:
      address: ":9100"

  metrics:
    prometheus:
      enabled: true
      entryPoint: metrics

  ports:
    web:
      port: 80
      expose: true
      exposedPort: 80
      protocol: TCP
    websecure:
      port: 443
      expose: true
      exposedPort: 443
      protocol: TCP
    metrics:
      port: 9100
      expose: true
      exposedPort: 9100
      protocol: TCP

  service:
    enabled: true
    type: NodePort
    ports:
      web:
        port: 80
        protocol: TCP
        targetPort: web
        nodePort: 30080
      websecure:
        port: 443
        protocol: TCP
        targetPort: websecure
        nodePort: 30443
      metrics:
        port: 9100
        protocol: TCP
        targetPort: metrics
        nodePort: 30910

  serviceMonitor:
    enabled: true
    additionalLabels: {}
    interval: 10s
    scrapeTimeout: 10s
