traefik:
  dashboard:
    enabled: true
  
  entryPoints:
    web:
      address: ":8000"   # Port alternatif pour HTTP
    websecure:
      address: ":8443"   # Port standard pour HTTPS (généralement libre)
    metrics:
      address: ":9090"   # Port alternatif pour les métriques
  
  metrics:
    prometheus:
      enabled: true
      entryPoint: metrics
  
  ports:
    web:
      port: 8000          # Correspond à l'entryPoint web
      expose:
        default: true
      exposedPort: 8000
      protocol: TCP
    websecure:
      port: 8443          # Correspond à l'entryPoint websecure
      expose:
        default: true
      exposedPort: 8443
      protocol: TCP
    metrics:
      port: 9090          # Correspond à l'entryPoint metrics
      expose:
        default: true
      exposedPort: 9090
      protocol: TCP
  
  service:
    enabled: true
    type: NodePort
    ports:
      web:
        port: 8000        # Même port que dans ports.web.port
        protocol: TCP
        targetPort: web
        nodePort: 31080
      websecure:
        port: 8443        # Même port que dans ports.websecure.port
        protocol: TCP
        targetPort: websecure
        nodePort: 31443
      metrics:
        port: 9090        # Même port que dans ports.metrics.port
        protocol: TCP
        targetPort: metrics
        nodePort: 31910
  
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 10s
    scrapeTimeout: 10s