traefik:
  dashboard:
    enabled: true
  
  entryPoints:
    web:
      address: ":8000"
    websecure:
      address: ":8443"
    metrics:
      address: ":9090"
  
  metrics:
    prometheus:
      enabled: true
      entryPoint: metrics
  
  ports:
    web:
      port: 8000
      expose: true
      exposedPort: 8000
      protocol: TCP
    websecure:
      port: 8443
      expose: true
      exposedPort: 8443
      protocol: TCP
    metrics:
      port: 9090
      expose: true
      exposedPort: 9090
      protocol: TCP
  
  service:
    enabled: true
    type: NodePort
    spec:
      ports:
        - name: web
          port: 8000
          protocol: TCP
          targetPort: 8000
          nodePort: 31080
        - name: websecure
          port: 8443
          protocol: TCP
          targetPort: 8443
          nodePort: 31443
        - name: metrics
          port: 9090
          protocol: TCP
          targetPort: 9090
          nodePort: 31910
  
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 10s
    scrapeTimeout: 10s