# Default values for todolist-frontend
replicaCount: 2

image:
  repository: soymustael/todolist-kub-frontend
  tag: "1.1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: todolist.local

env:
  REACT_APP_API_URL: "http://backend.todolist.cd ../.."

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
