apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: my-php-app:latest
          imagePullPolicy: Never
          env:
            - name: APP_ENV
              value: "dev"
            - name: APP_KEY
              value: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: app_database
            - name: DB_USERNAME
              value: app_user
            - name: DB_PASSWORD
              value: app_password
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
