apiVersion: v2
name: traefik-chart
description: A Helm chart for Traefik, a modern reverse proxy and load balancer
version: 0.1.0

dependencies:
  - name: traefik
    version: "35.4.0"
    repository: "https://helm.traefik.io/traefik"