apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-902
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AutomneB/kubquest-902.git
    targetRevision: raphael2
    path: 902-stack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-902
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
