replicaCount: 1

image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

podLabels:
  app.kubernetes.io/name: postgres-app
  app.kubernetes.io/instance: postgres
  app.kubernetes.io/version: "v1"
  app.kubernetes.io/component: db
  app.kubernetes.io/part-of: demo-voting

labels:
  app: demo-voting-app

# PostgreSQL specific configurations
postgresql:
  username: postgres
  password: examplepassword
  database: demo_voting

serviceAccount:
  create: false
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
