{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "todolist-backend.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todolist-backend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "todolist-backend.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
