name: Push on Epitech repository

on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  build:
    if: github.repository == 'AutomneB/kubquest-902'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git checkout $CI_COMMIT_REF_NAME
          git push --force https://github.com/EpitechMscProPromo2025/T-CLO-902-TLS_7.git $CI_COMMIT_REF_NAME
        env:
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
