apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todolist-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todolist-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "todolist-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todolist-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.env.REACT_APP_API_URL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
