postgresql:
  fullnameOverride: my-postgresql
  auth:
    username: myuser
    password: mypassword
    database: mydatabase
  primary:
    persistence:
      enabled: true
      size: 1Gi
  service:
    type: ClusterIP
