- name: Deploy CSI Azure Disk driver and StorageClass
  hosts: master
  become: true


  tasks:

    - name: Copier le fichier StorageClass azure-disk-sc.yaml sur le master
      copy:
        src: ../../persistanteVolume/azure-disk-sc.yaml
        dest: /home/adminuser/azure-disk-sc.yaml
        owner: adminuser
        group: adminuser
        mode: '0644'


    - name: Créer le secret azure-cloud-provider dans kube-system
      kubernetes.core.k8s:
        kubeconfig: /etc/kubernetes/admin.conf
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: azure-cloud-provider
            namespace: kube-system
          type: Opaque
          data:
            cloud-config: "{{ lookup('file', '../../persistanteVolume/sc-azure.json') | b64encode }}"

    - name: Ajouter le repo Helm Azure Disk CSI
      community.kubernetes.helm_repository:
        name: azuredisk-csi-driver
        repo_url: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts

    - name: Installer le driver Azure Disk CSI via Helm
      community.kubernetes.helm:
        name: azuredisk-csi
        chart_ref: azuredisk-csi-driver/azuredisk-csi-driver
        release_namespace: kube-system
        create_namespace: false
        kubeconfig: /etc/kubernetes/admin.conf


    - name: Appliquer le manifest StorageClass azure-disk
      command: kubectl apply -f /home/adminuser/azure-disk-sc.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf