### 📘 Playbook Ansible : Kubernetes Master Node Setup (master-playbook.yml)

- name: Init Kubernetes Master Node
  hosts: master
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Montrer sur quel hôte on tourne
      debug:
        msg: "Ce playbook s'exécute sur {{ inventory_hostname }}"

    - name: Installer les dépendances Python pour Kubernetes
      apt:
        name:
          - python3-pip
        state: present
        update_cache: true

    - name: Installer les modules Python nécessaires
      pip:
        name:
          - kubernetes
          - openshift
          - pyyaml

    - name: Initialiser le cluster Kubernetes
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Créer le dossier .kube
      file:
        path: /home/adminuser/.kube
        state: directory
        owner: "adminuser"
        group: "adminuser"
        mode: 0755

    - name: Copier le fichier de configuration kube
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/adminuser/.kube/config
        remote_src: yes
        owner: "adminuser"
        group: "adminuser"
        mode: 0644

    - name: Appliquer le plugin réseau Flannel
      become: true
      become_user: root
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Créer le dossier 902-stack
      file:
        path: /home/adminuser/902-stack
        state: directory
        owner: "adminuser"
        group: "adminuser"
        mode: 0755

    - name: Copier le dossier 902-stack vers le master
      copy:
        src: ../../902-stack/
        dest: /home/adminuser/902-stack/
        owner: adminuser
        group: adminuser
        mode: '0755'
    
    - name: Installer Helm v3.17.2
      shell: |
        curl -LO https://get.helm.sh/helm-v3.17.2-linux-amd64.tar.gz
        tar -xzvf helm-v3.17.2-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
        rm -rf linux-amd64 helm-v3.17.2-linux-amd64.tar.gz
      args:
        creates: /usr/local/bin/helm


    - name: Générer et afficher la commande kubeadm join
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Sauvegarder la commande kubeadm join dans un fichier partagé
      copy:
        dest: /home/adminuser/join-command.txt
        content: "{{ join_command.stdout }}"
        owner: adminuser
        group: adminuser
        mode: '0644'
