---
- name: Déployer Prometheus via Helm (kubernetes.core)
  hosts: master
  become: true
  tasks:
    - name: Ajouter le repo prometheus-community
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Installer kube-prometheus-stack
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values: "{{ lookup('file', '../../helm-values/prometheus/graf_pro_manifest.yml') | from_yaml }}"
        kubeconfig: /etc/kubernetes/admin.conf