### 📘 Playbook Ansible : Kubernetes Worker Node Setup (worker-playbook.yml)

- name: Join Kubernetes Cluster from Worker
  hosts: worker*
  become: true
  vars:
    kubeadm_join_cmd: "kubeadm join 10.0.1.4:6443 --token sgxb4u.p5b6sbhiwndtduxp --discovery-token-ca-cert-hash sha256:162766647805945bb4a2e086ba54b7e0c4ed9f2837ffc4f77d30833e1a7b7253"

  tasks:
    - name: Joindre le cluster Kubernetes
      command: "{{ kubeadm_join_cmd }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
