- name: Join Kubernetes Cluster from Worker
  hosts: worker*
  become: true
  vars:
    master_node: master  # correspond au nom dans l'inventaire Ansible

  tasks:
    - name: Récupérer la commande kubeadm join depuis le master
      slurp:
        src: /home/adminuser/join-command.txt
      delegate_to: "{{ master_node }}"
      register: join_file

    - name: Définir la variable join_command depuis le fichier
      set_fact:
        kubeadm_join_cmd: "{{ join_file.content | b64decode }}"

    - name: Joindre le cluster Kubernetes
      command: "{{ kubeadm_join_cmd }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
