- name: Deploy Keycloak on Kubernetes via Helm
  hosts: master
  become: true
  tasks:

    - name: Créer le namespace keycloak
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: keycloak
        state: present
        kubeconfig: /etc/kubernetes/admin.conf

    - name: Ajouter le dépôt Bitnami
      community.kubernetes.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Déployer Keycloak via Helm
      community.kubernetes.helm:
        name: keycloak
        chart_ref: bitnami/keycloak
        release_namespace: keycloak
        create_namespace: false
        kubeconfig: /etc/kubernetes/admin.conf
        values:
          auth:
            adminUser: admin
            adminPassword: admin123  # 🔒 à remplacer par un secret ou un vault dans une version sécurisée
          service:
            type: NodePort
          ingress:
            enabled: false
          postgresql:
            enabled: true
            auth:
              postgresPassword: keycloakdb
              password: keycloakpass
          replicaCount: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi

    - name: Attendre que Keycloak soit prêt
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: keycloak
        label_selectors:
          - app.kubernetes.io/name=keycloak
      register: keycloak_pods
      until: keycloak_pods.resources[0].status.containerStatuses[0].ready
      retries: 20
      delay: 15

    - name: Afficher le port NodePort de Keycloak
      shell: "kubectl get svc keycloak -n keycloak -o jsonpath='{.spec.ports[?(@.port==8080)].nodePort}'"
      register: keycloak_nodeport
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - debug:
        msg: >-
          Keycloak est déployé. Accédez à l'interface via :
          http://{{ hostvars[inventory_hostname]['ansible_host'] }}:{{ keycloak_nodeport.stdout }}
          Identifiants : admin / admin123
