### 📘 Playbook Ansible : Kubernetes Worker Node Setup (worker-playbook.yml)

- name: Join Kubernetes Cluster from Worker
  hosts: worker*
  become: true
  vars:
    kubeadm_join_cmd: "kubeadm join 10.0.1.4:6443 --token kn7iv0.dr3q4s618jo8cn9q --discovery-token-ca-cert-hash sha256:b79e5c8ed8db48b83dbe2db7f5ae82618a5a716d0bad675c0d42ceb1ebb9c24d"

  tasks:
    - name: Joindre le cluster Kubernetes
      command: "{{ kubeadm_join_cmd }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
