replicaCount: 1

image:
  repository: teryel/working-app
  tag: latest
  pullPolicy: IfNotPresent


podLabels:
  app.kubernetes.io/name: worker-app
  app.kubernetes.io/instance: worker
  app.kubernetes.io/version: "v1"
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: demo-voting


labels:
  app: demo-voting-app

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
