# Default values for todolist-backend
replicaCount: 2

image:
  repository: soymustael/todolist-kub-backend
  tag: "1.1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: traefik
  host: backend.todolist.local

env:
  DATABASE_URL: "postgresql://todolist:todolist123@postgres-service:5432/todolist"
  JWT_SECRET: "your-jwt-secret-key"
  PORT: "3000"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

livenessProbe:
  enabled: true
  path: /api/health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /api/health
  initialDelaySeconds: 5
  periodSeconds: 5
