apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AutomneB/kubquest-902.git'
    chart: redis-chart
    targetRevision: HEAD
    path: argocd/apps_charts/redis-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
