apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ton-repo.git'
    targetRevision: ArgoCD
    path: argocd/charts_apps/traefik
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
