replicaCount: 1

image:
  repository: teryel/working-app
  tag: latest
  pullPolicy: IfNotPresent


podLabels:
  app: voting-app
  name: worker-app-pod

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
